# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=2)),
                ('player_market_value', models.IntegerField(blank=True)),
                ('player_type', models.CharField(blank=True, max_length=1)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_injured', models.BooleanField(default=False)),
                ('is_missing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('team_num', models.IntegerField(blank=True)),
                ('team_flagPic', models.CharField(blank=True, max_length=100)),
                ('shirt_picture', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='app.Team'),
        ),
    ]
