# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_player_player_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points_value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
