# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_fantasyteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
