# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(blank=True),
        ),
    ]
