# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171127_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='captain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='capatain', to='app.Player'),
            preserve_default=False,
        ),
    ]
