# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171127_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyteam',
            name='captain',
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='captain',
            field=models.ManyToManyField(null=True, related_name='capatain', to='app.Player'),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='app.Player'),
        ),
    ]
