# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171127_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyteam',
            name='captain',
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capatain', to='app.Player'),
        ),
    ]
